### PR TITLE
stop adding the show name to an api search using a tv id

### PR DESCRIPTION
**Pull request by judhat2**
NZB Hydra would add the show name to a api search when using a TV ID.  Such as:
/api?t=tvsearch&extended=1&offset=0&limit=100&cat=5000&tvdbid=290853&ep=2&season=2&q=Fear+the+Walking+Dead

A successful search is returned on some indexers if the title is included.  However, some indexers return 0 results.  Removing the title works successfully on all indexers that support that particular ID.

Now the searches look like this:
/api?t=tvsearch&extended=1&offset=0&limit=100&cat=5000&tvdbid=290853&ep=2&season=2

This is mirrors the format that is used when NZB Hydra tries to find out what search types an indexer supports and the format that Sonarr uses.

### CODE REVIEW

**Comment by judhat2** [comment]
Ah, actually never mind.  I just realized this breaks doing a search when using the tv category with just the query search without using the tvdb id.

**Comment by theotherp** [comment]
I'll take a look. Pretty sure sonarr does this too.

I'm kinda stressed with work and leave for vacation on saturday, so don't expect anything before end of july.

**Comment by judhat2** [comment]
I think this fixes it correctly.  Please take a look after you vacation. Enjoy!

**Comment by theotherp** [comment]
Thanks for the help, but that would mean that ne query is never used. The problem / cause was somewhere else. I fixed it.

**Comment by theotherp** [comment]
I just pushed some changes to master that I though I'd already pushed last week. Hopefully there're not any more bugs in there, I'm leaving tomorrow...

**Comment by judhat2** [comment]
Thanks!  Enjoy your vacation

**Comment by theotherp** [comment]
Forecast predicts two weeks of rain, but I'll try my best, thanks.

**Pull request closed without merging**
