### PR TITLE
Win10 Creative update nssm fix

### PR DESCRIPTION
**Pull request by dlardo**
Ran into this myself, thought I would share.

### CODE REVIEW

**Comment by theotherp** [comment]
Thought I had had fixed this a long time ago. Thanks.

**Comment by theotherp** [comment]
The nssm.exe contained in the windows version is already the correct version: https://github.com/theotherp/nzbhydra-windows-releases/blob/master/WindowsService/nssm.exe

**Comment by dlardo** [comment]
I would guess the issue showed up on my system due to having Win10 and and having an old nssm.exe. Maybe when Win10 creative was released, the updated nssm.exe wasn't included in the nzbhydra auto-update process?

**Comment by theotherp** [comment]
Yeah, that's possible. Should be fixed now and for future installations.

**Pull request closed without merging**
