### PR TITLE
Update Dark theme, create grey theme

### PR DESCRIPTION
**Pull request by soundjester**
Added changes you suggested regarding renaming the dark theme to grey.  I have added the updates to the charts as well.

I could not figure out how to update the UI theme selection.  I thought updating the gulpfile and the config-fields-service.js would do it, but I am missing something somewhere.

### CODE REVIEW

**Comment by theotherp** [comment]
Thanks, I'll take a look.

**Comment by soundjester** [comment]
Cool.  These are all pretty much cosmetic.  I really dig the application (as do many, I'm sure), so I'm happy to contribute anything that you think is worthwhile.

**Comment by theotherp** [comment]
I'll use some of your code but add it manually. I'll leave this open until then.

I already added some code which adjusts the chart sizes to the amount of data shown.

**Comment by soundjester** [comment]
Since you are intimately familiar with your own code (and I am not), that is probably for the best.

**Comment by theotherp** [comment]
Thanks again. I didn't make any changes. I think it could be improved, it looks a bit whack, but at least it's dark.

**Comment by soundjester** [comment]
Yeah, that's alright. It's a meaningful amount of work for what essentially comes down to a personal preference.

Anybody who is even a little experienced with CSS and a terminal can make all the changes they like.  If I can ever figure out how to make a theme appear in the drop-down, I may contribute a self-contained CSS package.  Otherwise, it simply isn't that important or impactful to the core functionality of the application.

**Comment by theotherp** [comment]
https://github.com/theotherp/nzbhydra/commit/1cc69683f3bc88c1d68c0311bc07051e8ee83ede#diff-ae640bdee3a1be289767d56d102f150d

That's all there is to it. Just edit the less files next time, not the CSS files.

**Comment by soundjester** [comment]
man, that is so odd.  I changed that file at that location and nothing changed on my config interface.  I had to edit [here](https://github.com/theotherp/nzbhydra/blob/master/static/js/nzbhydra.js#L4465) to see any change (in the drop-down, anyway).

**Comment by theotherp** [comment]
You ran the gulpfile, right?

**Comment by soundjester** [comment]
Ah, that's what I was missing!

**Pull request closed without merging**
