### PR TITLE
Moaar Indexer

### LINKED ISSUE #88: Raise amount of indexer or n-indexer
I would like to have more and it seems that there is a hard coded limit, as I can't add more then 20 indexer.

Possible solutions would be to set it to a higher limit or make it infinite (n-indexer)

### PR DESCRIPTION
**Pull request by FailOPS**
Will fix #88

### CODE REVIEW

**Comment by theotherp** [comment]
Thanks, but increasing the value isn't much of a problem. I don't want to clutter the config page for the 0.1% who actually use more than 20 indexers. I will add a function to expand the page when more than 10/20/30 are needed.

**Comment by Mirabis** [comment]
Wouldn't it be possible to save it as lists in config, then adding a 'add more' button in the gui > which just appends another indexer?

Then you don't have to hardcode a limit?

**Comment by theotherp** [comment]
The limit isn't hard coded, but it's not possible to store them in an array. The reason is the way my config is implemented. I spent way more time on my config implementation than I'm willing to admit and in the end got so frustrated that I just stopped trying to implement arrays. This is the only thing in the config that needs it, anyway, so I decided it wasn't worth investing more time.

I'm now hiding a newznab indexer fieldgroup when any of the indexers before don't have a name.

**Comment by theotherp** [comment]
Made obsolete by ab8750bc0a42dd065ade0a16d157835454b678d7
Thanks anyway

**Pull request closed without merging**
